Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  (1..5).each do |i|
    config.vm.define "node#{i}" do |node|
      node.vm.hostname = "node#{i}"

      # Private network address: node1 => 192.168.56.110, node2 => 192.168.56.120, etc.
      node.vm.network "private_network", ip: "192.168.56.1#{i}0"

      # Forward SSH from VM guest port 22 to host port 2221..2225
      # node1 => 2221, node2 => 2222, etc.
      node.vm.network "forwarded_port", guest: 22, host: (2220 + i), id: "ssh"

      node.vm.provider "virtualbox" do |vb|
        vb.name = "node#{i}"
        vb.memory = 512
        vb.cpus = 1
      end

      # Now let Vagrant run Ansible
      node.vm.provision "ansible" do |ansible|
        ansible.playbook       = "../ansible/playbook.yml"
        ansible.inventory_path = "../ansible/inventory"
        ansible.become         = true
        ansible.limit          = "node#{i}"
        ansible.host_key_checking = false
      end
    end
  end
end

